#!/usr/bin/env bash

height=40

############## BAR ############## 
sketchybar -m --bar height=$height   \
                    width=$height    \
                    position=left    \
                    y_offset=10      \
                    padding_left=0   \
                    padding_right=15 \
                    margin=5         \
                    sticky=on        \
                    color=0x00000000

############## GLOBAL DEFAULTS ############## 
sketchybar -m --default updates=when_shown                    \
                        drawing=on                            \
                        icon.font="FiraCode Nerd Font:Regular:24.0"  \
                        icon.color=0xffa8a8a8                 \
                        label.font="FiraCode Nerd Font:Regular:24.0" \
                        label.color=0xffa8a8a8

############## SPACES PLUGIN  ############## 
~/.config/sketchybar/plugins/yabai-spaces.sh

############## CENTER ITEMS ############## 
# sketchybar -m --add event refresh_windows \
#               --add item windows center   \
#               --set windows script="~/.config/sketchybar/plugins/windows.sh" \
#               --subscribe windows front_app_switched space_change refresh_windows
#
# yabai -m signal --add event=space_changed label=windows action="sketchybar --trigger refresh_windows"
# yabai -m signal --add event=window_focused label=windows2 action="sketchybar --trigger refresh_windows"

############## FINALIZING THE SETUP ##############
sketchybar -m --update

echo "sketchybar configuration loaded.."
