#!/usr/bin/env bash

sketchybar --add event aerospace_workspace_change

height=40

############## BAR ##############
bar=(
                    height=$height
                    position=left
                    y_offset=10
                    margin=5
                    color=0x00000000
)
sketchybar --bar "${bar[@]}"

############## GLOBAL DEFAULTS ##############
defaults=(
                    updates=when_shown
                    drawing=on
                    background.drawing=on
                    background.height=$height
                    icon.font="FiraCode Nerd Font:Regular:24.0"
                    icon.align=center
                    icon.color=0xffa8a8a8
                    icon.highlight_color=0xf2cd2e4c
                    label.drawing=off

)
sketchybar --default "${defaults[@]}"

############## SPACES ##############
declare -A icons
icons["1-default"]=󰍹
icons["2-company"]=
icons["3-communication"]=󱩛
icons["4-term"]=
icons["5-build"]=
icons["6-vm"]=
icons["7-private"]=

for sid in $(aerospace list-workspaces --all); do
                    sketchybar --add item space.$sid right \
                                        --subscribe space.$sid aerospace_workspace_change \
                                        --set space.$sid \
                                        icon=${icons[$sid]-} \
                                        click_script="aerospace workspace $sid" \
                                        script="$CONFIG_DIR/plugins/aerospace-spaces.sh $sid"
done

############## FINALIZING THE SETUP ##############
sketchybar -m --update
